<?php

declare(strict_types=1);

/** @return array<string, mixed> */
return [
    'label' => 'Legal',
    'updated_note' => 'Describes how we process personal data and how we use cookies on this site.',
    'sections' => [
        [
            'title' => '1. Who we are',
            'body' => '<p>Operator of the <strong class="text-ink">Like HOME</strong> website (location: {city}). Contact for personal data questions: <a href="mailto:{email}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">{email}</a>.</p>',
        ],
        [
            'title' => '2. What data we collect',
            'body' => '<ul><li><strong class="text-ink">Data you provide:</strong> name, email, phone, messages, booking details (dates, number of guests, etc.) submitted via forms or email.</li><li><strong class="text-ink">Technical data:</strong> IP address, browser type, pages visited, timestamps — to the extent automatically generated by the server or analytics tools (if you accepted that category).</li><li><strong class="text-ink">Cookies:</strong> see the dedicated section below.</li></ul>',
        ],
        [
            'title' => '3. Purposes of processing',
            'body' => '<ul><li>Responding to requests and managing bookings.</li><li>Secure operation of the site and admin area (sessions, CSRF protection).</li><li>Improving experience and content (if you accepted analytics).</li><li>Measurement and relevant advertising campaigns (if you accepted advertising / marketing).</li><li>Legal obligations where applicable.</li></ul>',
        ],
        [
            'title' => '4. Legal basis (GDPR)',
            'body' => '<p>Processing may be necessary for contract performance or pre-contractual steps (booking), based on your consent (non-essential cookies, newsletter if offered), or on legitimate interest (security, anonymized aggregate statistics where permitted).</p>',
        ],
        [
            'title' => '5. Cookies and similar technologies',
            'body' => '<p class="mb-4">We use cookies and local storage (e.g. <code class="text-sm bg-black/[0.05] px-1 rounded">localStorage</code>) to remember your consent choices. You can change preferences anytime on the site (footer link “Cookie preferences”).</p><h3 class="text-ink font-semibold text-base mb-2">Categories</h3><ul class="space-y-3"><li><strong class="text-ink">Strictly necessary</strong> — PHP session for essential functions (e.g. administration), security; without them some features cannot work.</li><li><strong class="text-ink">Analytics</strong> — understanding how the site is used (e.g. Google Analytics), only if you accept.</li><li><strong class="text-ink">Advertising and marketing</strong> — conversion measurement, remarketing, personalized ads via partners (e.g. Google Ads, Meta), only if you accept.</li></ul><p class="mt-4 text-sm">Embedded content (e.g. maps) may set third-party cookies under their policies.</p>',
        ],
        [
            'title' => '6. Recipients and transfers',
            'body' => '<p>We may use hosting, email, and analytics / advertising providers. Some may be located outside the EEA; in such cases we ensure appropriate safeguards (standard contractual clauses, adequacy decisions, etc.) under applicable law.</p>',
        ],
        [
            'title' => '7. Retention period',
            'body' => '<p>We keep data as long as needed for the purposes above or as required by law (e.g. accounting). Cookies vary in duration; session cookies expire when you close the browser; others may last months per the provider.</p>',
        ],
        [
            'title' => '8. Your rights',
            'body' => '<p>Where the law allows, you may request access, rectification, erasure, restriction, portability, objection, and withdrawal of consent for processing based on consent. You may lodge a complaint with your supervisory authority.</p>',
        ],
        [
            'title' => '9. Children',
            'body' => '<p>The site is not intentionally directed at minors under 16 without parental consent.</p>',
        ],
    ],
];
