<?php

declare(strict_types=1);

/** @return array<string, mixed> */
return [
    'label' => 'Legal',
    'updated_note' => 'Structură aliniată cerințelor maib e-commerce pentru comerț electronic.',
    'intro' => '<p>Prezenții Termeni și Condiții de utilizare a magazinului online <a href="{site_url}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">{site_url}</a> sunt aplicabile comenzilor pentru achiziționarea serviciilor de cazare pe termen scurt (închiriere apartamente mobilate) oferite de compania <strong class="text-ink">{company_name}</strong> prin intermediul site-ului.</p><p>Pentru folosirea în bune condiții a site-ului, vă recomandăm familiarizarea cu atenție a Termenilor și Condițiilor prezentate. Ne rezervăm dreptul de a face modificări ale acestor prevederi, fără notificare prealabilă.</p>',
    'sections' => [
        [
            'title' => '1. Dispoziții generale',
            'body' => '<p>Acest site este deținut de <strong class="text-ink">{company_name}</strong>, IDNO {company_idno}. La plasarea comenzii (rezervării) în magazinul online, Cumpărătorul acceptă Termenii și Condițiile de prestare a serviciilor, care se bazează pe legislația Republicii Moldova.</p><p>Utilizarea website-ului presupune acceptarea Termenilor și Condițiilor propuse de către {company_name}, în conformitate cu Legea nr. 284/2004 privind Comerțul Electronic. Relațiile dintre client și prestator sunt stabilite în baza Legii nr. 105/2003 cu privire la Protecția drepturilor consumatorului și a altor acte normative adoptate în conformitate cu aceasta.</p><p>Prestatorul își rezervă dreptul de a modifica Termenii și Condițiile; Cumpărătorul este obligat să monitorizeze modificările publicate pe această pagină.</p>',
        ],
        [
            'title' => '2. Protecția datelor cu caracter personal',
            'body' => '<p>Prin utilizarea site-ului {site_url}, sunteți de acord cu colectarea și prelucrarea datelor cu caracter personal necesare procesării, confirmării și executării comenzilor.</p><p>Datele personale se prelucrează doar pentru scopuri legitime: furnizarea serviciului de cazare rezervat, comunicări privind rezervarea, securitatea site-ului, analiză (dacă ați acceptat cookie-urile de analiză) și, după caz, comunicări comerciale cu consimțământul dvs.</p><p>Informația cu date cu caracter personal este stocată și utilizată pentru perioada necesară atingerii scopurilor pentru care a fost colectată, în conformitate cu Legea nr. 133/2011 privind protecția datelor cu caracter personal.</p><p>Folosim măsuri de securitate pentru a preveni accesul neautorizat și a asigura utilizarea corectă a informației. Transmiterea datelor pe internet nu poate fi protejată în totalitate; prin urmare, unele operațiuni se efectuează pe propria răspundere a utilizatorului, în limitele rezonabile.</p><p>Detalii suplimentare: <a href="{privacy_url}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">Politica de confidențialitate</a>.</p>',
        ],
        [
            'title' => '3. Înregistrarea și achitarea comenzii',
            'body' => '<p>Rezervarea se efectuează online completând datele solicitate și bifând acceptarea prezentelor Termeni și Condiții. Plata comenzii este posibilă astfel:</p><ul><li><strong class="text-ink">Plată online cu cardul</strong> — prin serviciul securizat maib e-commerce (pagina băncii). După efectuarea plății veți primi confirmarea plății pe adresa dvs. de email. Poate fi aplicată o reducere de {online_discount}% față de totalul standard. Moneda tranzacției: {company_currency}.</li><li><strong class="text-ink">Plată la check-in</strong> — suma integrală se achită la sosire (numerar sau card), fără reducerea online.</li></ul><p>Plata online se face în condiții de siguranță maximă folosind cardul de plată. Procesatorul de plată maib folosește standardul de securitate <strong class="text-ink">3D-Secure</strong>: la plată puteți fi redirecționat pe pagina securizată maib, unde autentificarea deținătorului de card se face prin atribuirea unui cod unic de folosință pentru tranzacția online.</p><p><strong class="text-ink">Rambursarea</strong> mijloacelor bănești se efectuează doar pe cardul de plată care a fost folosit pentru achiziție, prin maib, în termenele bancare uzuale.</p><p>Pentru plată online, datele cardului sunt introduse exclusiv pe pagina securizată maib; {company_name} <strong class="text-ink">nu colectează și nu stochează</strong> numărul cardului, CVV/CVC sau alte date sensibile ale cardului. Informațiile sunt transmise criptat către sistemul de plăți.</p><p>La plată pot fi solicitate: numărul cardului (16 cifre), data expirării, codul CVC/CVV (3 cifre) și numele de pe card. Dacă valuta cardului diferă de {company_currency}, la convertire se aplică condițiile băncii emitente.</p>',
        ],
        [
            'title' => '4. Prestarea serviciilor de cazare',
            'body' => '<p>După confirmarea comenzii (rezervării), Clientul primește pe email detaliile sejurului: proprietatea rezervată, perioada check-in → check-out, numărul de oaspeți și instrucțiunile de acces.</p><p>Serviciul constă în punerea la dispoziție a apartamentului la adresa indicată în confirmare, pentru perioada rezervată. Accesul se face, de regulă, prin self check-in; codurile și detaliile practice sunt transmise înainte de sosire (inclusiv prin emailul de reminder check-in).</p><p>Orele standard de check-in și check-out sunt comunicate în confirmarea rezervării și pot varia ușor în funcție de proprietate. Beneficiarul plății pentru serviciile comercializate pe site este {company_name}.</p><p>Termenul de prestare poate fi afectat în situații excepționale (forță majoră, probleme tehnice neprevăzute etc.); vă vom informa în prealabil dacă apar astfel de situații.</p>',
        ],
        [
            'title' => '5. Anularea rezervării și rambursarea plății',
            'body' => '<p>Serviciile de cazare pe termen scurt au caracter personalizat (perioadă și apartament confirmate). Anularea și rambursarea se aplică conform condițiilor de mai jos, în spiritul protecției consumatorului (Legea nr. 105/2003).</p><p><strong class="text-ink">Rezervări plătite online (maib):</strong> anularea cu rambursare integrală a sumei achitate online este posibilă dacă anularea este solicitată cu cel puțin <strong class="text-ink">{refund_hours} ore</strong> înainte de ora de check-in (00:00 în ziua check-in). Sub acest termen, rambursarea nu este garantată automat; cazurile excepționale se analizează individual.</p><p><strong class="text-ink">Rezervări cu plată la check-in:</strong> anularea eliberează perioada rezervată; nu există sumă online de rambursat.</p><p>Contacte pentru anulare / ramburs: <a href="mailto:{email}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">{email}</a>, telefon {company_phones}. Cererile de rambursare pentru plăți online se procesează prin maib; termenul efectiv depinde de banca emitentă a cardului.</p>',
        ],
        [
            'title' => '6. Politica de confidențialitate',
            'body' => '<p>În conformitate cu Legea nr. 133/2011, {company_name} prelucrează date cu caracter personal cu bună-credință, în temeiul și în conformitate cu prevederile legale. Prelucrarea se realizează prin mijloace automatizate și manuale, cu respectarea cerințelor de securitate și confidențialitate.</p><p>Colectăm date furnizate la efectuarea comenzii: nume, email, telefon, detalii rezervare (perioadă, număr oaspeți). Datele sunt utilizate pentru administrarea site-ului, executarea rezervării, comunicări privind sejurul și, după caz, analiză sau marketing numai cu consimțământul dvs.</p><p>Nu dezvăluim datele personale terților fără acordul dvs., cu excepția cazurilor prevăzute de lege sau necesare procesării plății (ex. maib). <strong class="text-ink">Nu colectăm</strong> informații despre tranzacții card (număr card, expirare, țara emitentă) — acestea sunt procesate exclusiv de maib.</p><p>Pentru detalii complete, drepturile dvs. (acces, rectificare, ștergere etc.) și cookie-uri, consultați <a href="{privacy_url}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">Politica de confidențialitate</a> sau contactați <a href="mailto:{email}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">{email}</a>.</p>',
        ],
        [
            'title' => '7. Datele de contact',
            'body' => '<ul class="list-none pl-0 space-y-1"><li><strong class="text-ink">Denumirea juridică:</strong> {company_name}</li><li><strong class="text-ink">IDNO:</strong> {company_idno}</li><li><strong class="text-ink">Adresa juridică:</strong> {company_address}</li><li><strong class="text-ink">Adresa de prestare a serviciului:</strong> la adresa apartamentului rezervat (comunicată în confirmarea rezervării)</li><li><strong class="text-ink">Telefon de contact:</strong> {company_phones}</li><li><strong class="text-ink">Email de contact:</strong> <a href="mailto:{email}" class="text-ink font-semibold underline decoration-black/20 underline-offset-4 hover:decoration-ink">{email}</a></li><li><strong class="text-ink">Cont bancar ({company_currency}):</strong> {company_iban} · BIC {company_bic}</li></ul><p>Pentru litigii se aplică legea Republicii Moldova.</p>',
        ],
    ],
];
